/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaldb;

/**
 *
 * @author raksh
 */
public class DoctorMain1 extends javax.swing.JFrame {

    /**
     * Creates new form DoctorMain1
     */
    public DoctorMain1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDoc = new javax.swing.JButton();
        remDoc = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        viewAll1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setPreferredSize(new java.awt.Dimension(400, 332));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addDoc.setBackground(new java.awt.Color(255, 255, 255));
        addDoc.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        addDoc.setText("2. Add Doctor");
        addDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDocActionPerformed(evt);
            }
        });
        getContentPane().add(addDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        remDoc.setBackground(new java.awt.Color(255, 255, 255));
        remDoc.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        remDoc.setText("3. Remove Doctor");
        remDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remDocActionPerformed(evt);
            }
        });
        getContentPane().add(remDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        goBack.setBackground(new java.awt.Color(255, 255, 255));
        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicaldb/logout.png"))); // NOI18N
        goBack.setText("Go Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Doctors");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        viewAll1.setBackground(new java.awt.Color(255, 255, 255));
        viewAll1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        viewAll1.setText("1. View All Doctors");
        viewAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAll1ActionPerformed(evt);
            }
        });
        getContentPane().add(viewAll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicaldb/doc.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicaldb/white.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDocActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddDoctor().setVisible(true);
    }//GEN-LAST:event_addDocActionPerformed

    private void remDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remDocActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new DeleteDoctor().setVisible(true);
    }//GEN-LAST:event_remDocActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home1().setVisible(true);
    }//GEN-LAST:event_goBackActionPerformed

    private void viewAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAll1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new DisplayDoctors().setVisible(true);
        
    }//GEN-LAST:event_viewAll1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorMain1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorMain1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoc;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton remDoc;
    private javax.swing.JButton viewAll1;
    // End of variables declaration//GEN-END:variables
}
