/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaldb;

import javax.swing.JOptionPane;

/**
 *
 * @author raksh
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientAdd = new javax.swing.JButton();
        MedRec = new javax.swing.JButton();
        App = new javax.swing.JButton();
        DocInfo = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Bills = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        CliDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PatientAdd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        PatientAdd.setText("1. Add New Patient Record");
        PatientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAddActionPerformed(evt);
            }
        });

        MedRec.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        MedRec.setText("2. Medical Record");
        MedRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedRecActionPerformed(evt);
            }
        });

        App.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        App.setText("3. Appointments");
        App.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppActionPerformed(evt);
            }
        });

        DocInfo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        DocInfo.setText("4. Doctors Information");
        DocInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocInfoActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Bills.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        Bills.setText("5. Bills");
        Bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillsActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        Title.setText("Clinic Name");

        CliDel.setText("Clinic Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(CliDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Bills)
                        .addComponent(DocInfo)
                        .addComponent(App)
                        .addComponent(PatientAdd)
                        .addComponent(MedRec)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(PatientAdd)
                .addGap(18, 18, 18)
                .addComponent(MedRec)
                .addGap(18, 18, 18)
                .addComponent(App)
                .addGap(18, 18, 18)
                .addComponent(DocInfo)
                .addGap(18, 18, 18)
                .addComponent(Bills)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CliDel)
                    .addComponent(Logout))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppActionPerformed
        // TODO add your handling code here:
        new appointment().setVisible(true);
    }//GEN-LAST:event_AppActionPerformed

    private void DocInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocInfoActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int  a;
        a = JOptionPane.showConfirmDialog(null,"Do you reall want to logout?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new login().setVisible(true);
        }
        
    }//GEN-LAST:event_LogoutActionPerformed

    private void PatientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAddActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new newpatient().setVisible(true);
    }//GEN-LAST:event_PatientAddActionPerformed

    private void MedRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedRecActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new medicalrecords().setVisible(true);
    }//GEN-LAST:event_MedRecActionPerformed

    private void BillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new bill().setVisible(true);
    }//GEN-LAST:event_BillsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton App;
    private javax.swing.JButton Bills;
    private javax.swing.JButton CliDel;
    private javax.swing.JButton DocInfo;
    private javax.swing.JButton Logout;
    private javax.swing.JButton MedRec;
    private javax.swing.JButton PatientAdd;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
